<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="3" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-02T09:42:56 CST" name="Suite" finished-at="2024-02-02T09:43:28 CST" duration-ms="31675">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.loginErrorValidation()[pri:0, instance:KavyaSaiAcadamey.Tests.ErrorValidationsTest@5c6648b0]" name="loginErrorValidation" class="KavyaSaiAcadamey.Tests.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2024-02-02T09:42:56 CST" name="SubmitOrderTest" finished-at="2024-02-02T09:42:56 CST" duration-ms="18">
    </test> <!-- SubmitOrderTest -->
    <test started-at="2024-02-02T09:42:56 CST" name="ErrorValidationsTest" finished-at="2024-02-02T09:43:28 CST" duration-ms="31675">
      <class name="KavyaSaiAcadamey.Tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:KavyaSaiAcadamey.Tests.ErrorValidationsTest@5c6648b0]" started-at="2024-02-02T09:42:56 CST" name="launchApplication" finished-at="2024-02-02T09:43:08 CST" duration-ms="11718" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:KavyaSaiAcadamey.Tests.ErrorValidationsTest@5c6648b0]" started-at="2024-02-02T09:43:08 CST" name="loginErrorValidation" finished-at="2024-02-02T09:43:08 CST" duration-ms="654" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at KavyaSaiAcadamey.Tests.ErrorValidationsTest.loginErrorValidation(ErrorValidationsTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:KavyaSaiAcadamey.Tests.ErrorValidationsTest@5c6648b0]" started-at="2024-02-02T09:43:08 CST" name="tearDown" finished-at="2024-02-02T09:43:12 CST" duration-ms="3119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:KavyaSaiAcadamey.Tests.ErrorValidationsTest@5c6648b0]" started-at="2024-02-02T09:43:12 CST" name="launchApplication" finished-at="2024-02-02T09:43:25 CST" duration-ms="13536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:KavyaSaiAcadamey.Tests.ErrorValidationsTest@5c6648b0]" started-at="2024-02-02T09:43:25 CST" name="loginErrorValidation" finished-at="2024-02-02T09:43:26 CST" duration-ms="630" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:KavyaSaiAcadamey.Tests.ErrorValidationsTest@5c6648b0]" started-at="2024-02-02T09:43:26 CST" name="tearDown" finished-at="2024-02-02T09:43:28 CST" duration-ms="1925" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- KavyaSaiAcadamey.Tests.ErrorValidationsTest -->
    </test> <!-- ErrorValidationsTest -->
  </suite> <!-- Suite -->
</testng-results>
